#!/bin/bash
cd $PWD

files=$(git diff --cached --name-only --diff-filter=ACM | grep ".js$")
if [ "$files" = "" ]; then
  exit 0
fi

pass=true

if [ ! -f ./node_modules/.bin/eslint ]; then
  echo "eslint binary not found! Skipping tests."
  exit 0
fi

printf "\nRunning eslint on .js files:\n"

for file in ${files}; do
  ./node_modules/.bin/eslint --cache ${file}
  if [ $? -ne 0 ]; then
    printf "\033[31meslint Failed: %s\033[0m\n" "${file}"
    pass=false
  else
    printf "\033[32meslint Passed: %s\033[0m\n" "${file}"
  fi
done

if $pass; then
  printf "\n\033[42mCOMMIT SUCCEEDED\033[0m\n\n"
else
  printf "\n\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass validation tests but do not. Please fix the errors and try again.\n\n"
  exit 1
fi
